name: 'CI'

on:
  push:
    branches:
      - 'master'
      - 'develop'
  pull_request:
    branches:
      - 'master'
      - 'develop'

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: Wandalen/wretry.action@master
        with:
          action: actions/setup-java@v3
          with: |
            java-version: 11
            distribution: 'temurin'
          attempt_limit: 3
          attempt_delay: 2000

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/master' && github.ref != 'refs/heads/develop'}}
          build-scan-publish: 'true'
          build-scan-terms-of-use-url: 'https://gradle.com/terms-of-service'
          build-scan-terms-of-use-agree: 'yes'