name: 'CI'

on:
  push:
    branches:
      - 'main'
      - 'newbranch'
  pull_request:
    branches:
      - 'main'
      - 'newbranch'

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{runner.os}}