name: 'test-every-push'

# 푸시하거나 pull request가 머지될 때 workflow 실행
on:
  push
  pull_request

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - run: ls -al
      - uses: actions/checkout@v3
        with:
          path: project
      - run: cd project
      - run: ls -al

  cache:
    runs-on: ubuntu-latest
    steps:
      - run: ls -al
